### ISSUE TITLE
DeadAirAITweaks mod 

### ISSUE THREAD

**Issue by zeroaleh** [kuertee/x4-mod-da-ku-ai-tweaks#8]
ware to get DeadAirAITweaks mod the web site for download is not working on GitHub help pls

https://github.com/DeadAirRT/deadairaitweaks

**Comment by kuertee** [comment]
get it from this repo - if you're familiar with github. or from nexus mods. links are in the read-me.

**Comment by zeroaleh** [comment]
Thank you so much
